"use strict";
const RequestResults = require("../constants/RequestResults");
const Device = require("../resources/Device");
const Utils = require("../utils/Utils");

let _token = null;
let _requester = null;

module.exports = {

    /**
     * Initialize the service with a token and HTTP requester.
     * @param {string} token - Token to use when communicating with backend
     * @param {object} requester - A requester object that handles communicating
     * with the backend
     */
    initialize: function(token, requester) {
        Utils.assertValidToken(token);
        Utils.assertValidRequester(requester);
        _token = token;
        _requester = requester;
    },

    getTimestamp: function(callback) {
        Utils.assertValidToken(_token);
        const URL = _requester.getFullEndpoint("/devices/timestamp");

        const req = _requester.getRequest(URL, _token);
        const innerCb = function(status, webResp) {
            if (status === RequestResults.PENDING) {
                return;
            } else if (!Utils.isCallback(callback)) {
                return;
            }

            const resp = Utils.getDefaultApiResp(status, webResp);
            if (!resp.timeout) {
                const body = webResp.body;
                if (status === RequestResults.SUCCESS) {
                    resp.timestamp = body.server_timestamp;
                } else if (status === RequestResults.FAILURE) {
                    if (body && body.errors) {
                        resp.error = body.errors[0];
                    }
                }
            }
            callback(resp);
        };
        _requester.execute(req, innerCb);
    },

    /* TODO(rrk) Remove deprecated params in v0.8.0*/

    /**
     * Register the device with the iobeam.
     * @param {integer} projectId - Project ID for the device
     * @param {function} [callback] - Callback for the API response
     * @param {string|Device} [deviceId] - Desired device ID (deprecated) or Device with desired specs.
     * Otherwise randomly generated by iobeam.
     * @param {string} [deviceName] - DEPRECATED: Use Device object in previous parameter. Desired device name. Otherwise set to provided
     * device id, or randomly generated by iobeam.
     * @param {string} [deviceType] - DEPRECATED: Use Device object. Desired device type
     */
    register: function(projectId, callback, deviceId, deviceName, deviceType) {
        Utils.assertValidToken(_token);
        const URL = _requester.getFullEndpoint("/devices");
        let did = deviceId || null;
        let dname = deviceName || null;
        let dtype = deviceType || null;
        if (deviceId instanceof Device) {
            did = deviceId.getId();
            dname = deviceId.getName();
            dtype = deviceId.getType();
        } else if (deviceId) {
            console.warn("Please use Device instead of passing a string.");
        }

        const reqBody = {project_id: projectId};
        if (did !== null) {
            reqBody.device_id = did;
        }
        if (dname !== null) {
            reqBody.device_name = dname;
        }
        if (dtype !== null) {
            reqBody.device_type = dtype;
        }

        const context = {
            projectId: projectId,
            device: new Device(did, dname, dtype),
            deviceId: did,
            deviceName: dname,
            deviceType: dtype
        };
        const req = _requester.postRequest(URL, reqBody, _token);
        const bodyHandler = function(resp, body, status) {
            if (status === RequestResults.SUCCESS) {
                resp.device = new Device(body.device_id, body.device_name, body.device_type, body.created);
                /* TODO(rrk): Deprecated, remove in v0.8.0 */
                resp.device.device_id = resp.device.getId();
                resp.device.device_name = resp.device.getName();
                resp.device.created = resp.device.getCreated();
                if (body.device_type) {
                    resp.device.device_type = resp.device.getType();
                }
            } else if (status === RequestResults.FAILURE) {
                if (body && body.errors) {
                    resp.error = body.errors[0];
                }
            }
        };
        const innerCb = Utils.createInnerCb(callback, context, bodyHandler);
        _requester.execute(req, innerCb);
    }

};
